# Development overrides
services:
  streaming-server:
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
    environment:
      - RELOAD=true
      - DEBUG=true
      - LOG_LEVEL=debug
    command: ["python", "/app/src/api/streaming_server.py"]

  nginx:
    volumes:
      - ./static:/usr/share/nginx/html/static:ro
